//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ASPNETDBModel", "FK_tagsToPresentation_Presentations", "Presentations", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SlideX.Models.Presentation), "tagsToPresentation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SlideX.Models.tagsToPresentation), true)]
[assembly: EdmRelationshipAttribute("ASPNETDBModel", "FK_tagsToPresentation_PresentationTags", "PresentationTags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SlideX.Models.PresentationTag), "tagsToPresentation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SlideX.Models.tagsToPresentation), true)]

#endregion

namespace SlideX.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ASPNETDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ASPNETDBEntities object using the connection string found in the 'ASPNETDBEntities' section of the application configuration file.
        /// </summary>
        public ASPNETDBEntities() : base("name=ASPNETDBEntities", "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(string connectionString) : base(connectionString, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ASPNETDBEntities object.
        /// </summary>
        public ASPNETDBEntities(EntityConnection connection) : base(connection, "ASPNETDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Presentation> Presentations
        {
            get
            {
                if ((_Presentations == null))
                {
                    _Presentations = base.CreateObjectSet<Presentation>("Presentations");
                }
                return _Presentations;
            }
        }
        private ObjectSet<Presentation> _Presentations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PresentationTag> PresentationTags
        {
            get
            {
                if ((_PresentationTags == null))
                {
                    _PresentationTags = base.CreateObjectSet<PresentationTag>("PresentationTags");
                }
                return _PresentationTags;
            }
        }
        private ObjectSet<PresentationTag> _PresentationTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tagsToPresentation> tagsToPresentations
        {
            get
            {
                if ((_tagsToPresentations == null))
                {
                    _tagsToPresentations = base.CreateObjectSet<tagsToPresentation>("tagsToPresentations");
                }
                return _tagsToPresentations;
            }
        }
        private ObjectSet<tagsToPresentation> _tagsToPresentations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Presentations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPresentations(Presentation presentation)
        {
            base.AddObject("Presentations", presentation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PresentationTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPresentationTags(PresentationTag presentationTag)
        {
            base.AddObject("PresentationTags", presentationTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tagsToPresentations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotagsToPresentations(tagsToPresentation tagsToPresentation)
        {
            base.AddObject("tagsToPresentations", tagsToPresentation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="Presentation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Presentation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Presentation object.
        /// </summary>
        /// <param name="presentationId">Initial value of the PresentationId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static Presentation CreatePresentation(global::System.Guid presentationId, global::System.Guid userId, global::System.String title)
        {
            Presentation presentation = new Presentation();
            presentation.PresentationId = presentationId;
            presentation.UserId = userId;
            presentation.Title = title;
            return presentation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PresentationId
        {
            get
            {
                return _PresentationId;
            }
            set
            {
                if (_PresentationId != value)
                {
                    OnPresentationIdChanging(value);
                    ReportPropertyChanging("PresentationId");
                    _PresentationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PresentationId");
                    OnPresentationIdChanged();
                }
            }
        }
        private global::System.Guid _PresentationId;
        partial void OnPresentationIdChanging(global::System.Guid value);
        partial void OnPresentationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PresentationContent
        {
            get
            {
                return _PresentationContent;
            }
            set
            {
                OnPresentationContentChanging(value);
                ReportPropertyChanging("PresentationContent");
                _PresentationContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PresentationContent");
                OnPresentationContentChanged();
            }
        }
        private global::System.String _PresentationContent;
        partial void OnPresentationContentChanging(global::System.String value);
        partial void OnPresentationContentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ASPNETDBModel", "FK_tagsToPresentation_Presentations", "tagsToPresentation")]
        public EntityCollection<tagsToPresentation> tagsToPresentations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tagsToPresentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "tagsToPresentation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tagsToPresentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "tagsToPresentation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="PresentationTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PresentationTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PresentationTag object.
        /// </summary>
        /// <param name="tagId">Initial value of the TagId property.</param>
        /// <param name="tagTitle">Initial value of the TagTitle property.</param>
        public static PresentationTag CreatePresentationTag(global::System.Guid tagId, global::System.String tagTitle)
        {
            PresentationTag presentationTag = new PresentationTag();
            presentationTag.TagId = tagId;
            presentationTag.TagTitle = tagTitle;
            return presentationTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Guid _TagId;
        partial void OnTagIdChanging(global::System.Guid value);
        partial void OnTagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TagTitle
        {
            get
            {
                return _TagTitle;
            }
            set
            {
                OnTagTitleChanging(value);
                ReportPropertyChanging("TagTitle");
                _TagTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TagTitle");
                OnTagTitleChanged();
            }
        }
        private global::System.String _TagTitle;
        partial void OnTagTitleChanging(global::System.String value);
        partial void OnTagTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ASPNETDBModel", "FK_tagsToPresentation_PresentationTags", "tagsToPresentation")]
        public EntityCollection<tagsToPresentation> tagsToPresentations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tagsToPresentation>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "tagsToPresentation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tagsToPresentation>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "tagsToPresentation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ASPNETDBModel", Name="tagsToPresentation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tagsToPresentation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tagsToPresentation object.
        /// </summary>
        /// <param name="matchId">Initial value of the MatchId property.</param>
        /// <param name="presentationId">Initial value of the PresentationId property.</param>
        /// <param name="tagId">Initial value of the TagId property.</param>
        public static tagsToPresentation CreatetagsToPresentation(global::System.Guid matchId, global::System.Guid presentationId, global::System.Guid tagId)
        {
            tagsToPresentation tagsToPresentation = new tagsToPresentation();
            tagsToPresentation.MatchId = matchId;
            tagsToPresentation.PresentationId = presentationId;
            tagsToPresentation.TagId = tagId;
            return tagsToPresentation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MatchId
        {
            get
            {
                return _MatchId;
            }
            set
            {
                if (_MatchId != value)
                {
                    OnMatchIdChanging(value);
                    ReportPropertyChanging("MatchId");
                    _MatchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MatchId");
                    OnMatchIdChanged();
                }
            }
        }
        private global::System.Guid _MatchId;
        partial void OnMatchIdChanging(global::System.Guid value);
        partial void OnMatchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PresentationId
        {
            get
            {
                return _PresentationId;
            }
            set
            {
                OnPresentationIdChanging(value);
                ReportPropertyChanging("PresentationId");
                _PresentationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PresentationId");
                OnPresentationIdChanged();
            }
        }
        private global::System.Guid _PresentationId;
        partial void OnPresentationIdChanging(global::System.Guid value);
        partial void OnPresentationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                OnTagIdChanging(value);
                ReportPropertyChanging("TagId");
                _TagId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TagId");
                OnTagIdChanged();
            }
        }
        private global::System.Guid _TagId;
        partial void OnTagIdChanging(global::System.Guid value);
        partial void OnTagIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ASPNETDBModel", "FK_tagsToPresentation_Presentations", "Presentations")]
        public Presentation Presentation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Presentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "Presentations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Presentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "Presentations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Presentation> PresentationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Presentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "Presentations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Presentation>("ASPNETDBModel.FK_tagsToPresentation_Presentations", "Presentations", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ASPNETDBModel", "FK_tagsToPresentation_PresentationTags", "PresentationTags")]
        public PresentationTag PresentationTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PresentationTag>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "PresentationTags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PresentationTag>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "PresentationTags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PresentationTag> PresentationTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PresentationTag>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "PresentationTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PresentationTag>("ASPNETDBModel.FK_tagsToPresentation_PresentationTags", "PresentationTags", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
